import type { Metadata } from "next";
import { Geist, Geist_Mono, Shalimar } from "next/font/google";
import "./globals.scss";
import LayoutClient from "./layout.c";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const shalimar = Shalimar({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-shalimar",
});

import { Playfair_Display } from "next/font/google";

export const silkSerif = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-silk-serif",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${silkSerif.variable} ${shalimar.variable}`}
      >
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
